services:
  postgres:
    image: postgres:17-alpine
    container_name: flowforge_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: flowforge
    ports:
      - "5432:5432"
    volumes:
      - flowforge_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  flowforge_postgres_data:
